#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export PATH=$PATH:~/bin

setopt interactivecomments

export EDITOR=vi
if which vim >/dev/null ; then
  export EDITOR=vi
  alias vi=vim
fi

alias rm='nocorrect rm'
alias ping='nocorrect ping'
